filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/Hello.json
  tags: ["txt_logs"]

- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/LA.json
  tags: ["json_logs"]

output.logstash:
  hosts: ["logstash:5044"]
