- name: Install Filebeat in Docker
  docker_container:
    name: filebeat
    image: docker.elastic.co/beats/filebeat:7.15.2
    state: started
    restart_policy: always
    volumes:
      - /home/richa/Ansible1/esdata/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /mnt/e/ELK/Hello.json:/usr/share/filebeat/Hello.json
      - /mnt/e/ELK/LA.json:/usr/share/filebeat/LA.json
    ports:
      - "5044:5044"
    command: ["filebeat", "-e", "-strict.perms=false"]
    networks:
      - name: my-network

   




